package sitha.rupp.service;
import java.util.ArrayList;
import java.util.List;
import org.springframework.jdbc.support.rowset.SqlRowSet;
import sitha.rupp.configuration.GenericDaSupport;
import sitha.rupp.model.rpt_0013_policy_search_model;

public class rpt_0013_policy_searchServices extends GenericDaSupport {

	String sql="SELECT  \r\n" + 
			"--P.POLH_SYS_ID AS POLH_SYS_ID,\r\n" + 
			"--P.POLH_EXTNUM AS POLH_EXTNUM,\r\n" + 
			"--P.POLH_SRNUM AS POLH_SRNUM,\r\n" + 
			"--P.POLH_STATUS AS POLH_STATUS,\r\n" + 
			"--P.POLH_POST_PERIOD AS POLH_POST_PERIOD,\r\n" + 
			"ROW_NUMBER() OVER (order by P.POLH_ISSDT) AS No\r\n" + 
			"--P.POLH_SRNUM AS SEQ,\r\n" + 
			"--P.POLH_POLNUM AS QUOTATION_NO,\r\n" + 
			",P.POLH_COB AS PRODUCT_CODE\r\n" + 
			",P.POLH_POLNUM AS POLICY_NUMBER\r\n" + 
			",P.POLH_EXTNUM\r\n" + 
			",FN_GET_POLICY_FORMAT(P.POLH_POLNUM,P.POLH_COB,P.POLH_EXTNUM) AS DISPLAY_POLICY\r\n" + 
			",UPPER(P.POLH_ASSRDNM) AS INSURED_NAME\r\n" + 
			"--,P.POLH_DEBIT_PARTY\r\n" + 
			",P.POLH_CLIENT\r\n" + 
			",(SELECT C.CVBR_BRANCH_NAME FROM RAIMS.IBM_PARTY_BRANCH C WHERE C.CVBR_BRANCH_CODE=P.POLH_CLIENT) AS CLIENT_NAME\r\n" + 
			",P.POLH_DEBIT_PARTY AS INTERMEDIARY_CODE\r\n" + 
			",(SELECT C.CVBR_BRANCH_NAME FROM RAIMS.IBM_PARTY_BRANCH C WHERE C.CVBR_BRANCH_CODE=P.POLH_DEBIT_PARTY) AS INTERMEDIARY_NAME \r\n" + 
			",G.IH_JRNL_TYPE||P.POLH_PREM_DOCNUM AS INVOICE\r\n" + 
			",P.POLH_SI_FC AS SUM_INSURED \r\n" + 
			",POLH_PREM_BC AS GROSS_PREMIUM\r\n" + 
			",ROUND(P.POLH_PREM_BC+P.POLH_ADJ_PREM_BC,2) AS NET_PREMIUM \r\n" + 
			",P.POLH_ADJ_PREM_BC AS ADJUST_PREMIUM \r\n" + 
			",P.POLH_FEES3_BC AS ADMIN_FEE\r\n" + 
			",(P.POLH_PREM_BC+P.POLH_ADJ_PREM_BC + P.POLH_FEES3_BC) AS TOTAL\r\n" + 
			",TO_CHAR(P.POLH_ISSDT,'DD-MON-YYYY') AS ISSUE_DATE\r\n" + 
			",TO_CHAR(P.POLH_STPERIOD,'DD-MON-YYYY') EFFECTIVE_DATE\r\n" + 
			",TO_CHAR(P.POLH_ENDPERIOD,'DD-MON-YYYY') EXPIRY_DATE\r\n" + 
			",P.POLH_EMPLOYEE AS ISSUE_BY\r\n" + 
			",(SELECT U.USER_SHORT_NAME FROM RAIMS.MMGR_USERS U WHERE U.USER_ID=P.POLH_EMPLOYEE) AS USER_NAME\r\n" + 
			"--,P.*\r\n" + 
			"--(SELECT distinct(PINTMV_MOD_DESC) FROM INT_UW_PINT_MOTOR M WHERE M.PINTMV_PINT_SYS_ID=P.POLH_SYS_ID) AS DESCRIPTION\r\n" + 
			"--,M.PINTMV_MAKE_MODEL AS PINTMV_MAKE_MODEL\r\n" + 
			"--,M.PINTMV_MOD_DESC AS DESCRIPTION\r\n" + 
			",P.POLH_UWYR\r\n" + 
			"FROM RAIMS.INT_UW_POLH P \r\n" + 
			"--LEFT JOIN RAIMS.INT_UW_PINT_MOTOR M ON P.POLH_SYS_ID=M.PINTMV_PINT_SYS_ID\r\n" + 
			"INNER JOIN RAIMS.GLT_INTERFACE_HEAD G ON P.POLH_PREM_DOCNUM=G.IH_DOC_NO AND P.POLH_SYS_ID=G.IH_POLH_SYS_ID\r\n" + 
			"ORDER BY P.POLH_ISSDT DESC \r\n"+
			"--WHERE \r\n" + 
			"--P.POLH_EXTNUM=M.PINTMV_EXTNUM AND\r\n" + 
			"--P.POLH_STATUS IS NOT NULL AND\r\n" + 
			"--P.POLH_ISSDT BETWEEN '01-APR-2020' AND '30-APR-2020';\r\n" + 
			"--P.POLH_ISSDT BETWEEN '01-JUN-2020' AND '31-AUG-2020'; \r\n" + 
			"--AND P.POLH_DISPLAY_POLNUM='P/01/PV00/20/0555/000/00';\r\n" + 
			"--AND P.POLH_DISPLAY_POLNUM='P/01/MC00/20/0043/000/00';\r\n" + 
			"--P.POLH_DISPLAY_POLNUM='P/01/PV00/20/0555/000/00'";
	
	public List<rpt_0013_policy_search_model> getPolicyListALL(){
		//String sql="";
		List<rpt_0013_policy_search_model>ls=new ArrayList<rpt_0013_policy_search_model>();
		SqlRowSet row=getJdbcTemplate().queryForRowSet(sql);
		while(row.next()){
			rpt_0013_policy_search_model policy =new rpt_0013_policy_search_model();
			
			policy.setNO(row.getString("NO"));
			policy.setPRODUCT_CODE(row.getString("PRODUCT_CODE"));
			policy.setPOLICY_NUMBER(row.getString("POLICY_NUMBER"));
			policy.setPOLH_EXTNUM(row.getString("POLH_EXTNUM"));
			policy.setDISPLAY_POLICY(row.getString("DISPLAY_POLICY"));
			policy.setINSURED_NAME(row.getString("INSURED_NAME"));
			policy.setPOLH_CLIENT(row.getString("POLH_CLIENT"));
			policy.setCLIENT_NAME(row.getString("CLIENT_NAME"));
			policy.setINTERMEDIARY_CODE(row.getString("INTERMEDIARY_CODE"));
			policy.setINTERMEDIARY_NAME(row.getString("INTERMEDIARY_NAME"));
			policy.setINVOICE(row.getString("INVOICE"));
			policy.setSUM_INSURED(row.getDouble("SUM_INSURED"));
			policy.setGROSS_PREMIUM(row.getDouble("GROSS_PREMIUM"));
			policy.setNET_PREMIUM(row.getDouble("NET_PREMIUM"));
			policy.setADJUST_PREMIUM(row.getDouble("ADJUST_PREMIUM"));
			policy.setADMIN_FEE(row.getDouble("ADMIN_FEE"));
			policy.setTOTAL(row.getDouble("TOTAL"));
			policy.setISSUE_DATE(row.getString("ISSUE_DATE"));
			policy.setEFFECTIVE_DATE(row.getString("EFFECTIVE_DATE"));
			policy.setEXPIRY_DATE(row.getString("EXPIRY_DATE"));
			policy.setISSUE_BY(row.getString("ISSUE_BY"));
			policy.setUSER_NAME(row.getString("USER_NAME"));
			policy.setPOLH_UWYR(row.getString("POLH_UWYR"));

			ls.add(policy);
		}
		//System.out.println(ls.toString());
		return ls;
	}
	
/*
	SELECT  
	--P.POLH_SYS_ID AS POLH_SYS_ID,
	--P.POLH_EXTNUM AS POLH_EXTNUM,
	--P.POLH_SRNUM AS POLH_SRNUM,
	--P.POLH_STATUS AS POLH_STATUS,
	--P.POLH_POST_PERIOD AS POLH_POST_PERIOD,
	ROW_NUMBER() OVER (order by P.POLH_ISSDT) AS No
	--P.POLH_SRNUM AS SEQ,
	--P.POLH_POLNUM AS QUOTATION_NO,
	,P.POLH_COB AS PRODUCT_CODE
	,P.POLH_POLNUM AS POLICY_NUMBER
	,P.POLH_EXTNUM
	,FN_GET_POLICY_FORMAT(P.POLH_POLNUM,P.POLH_COB,P.POLH_EXTNUM) AS DISPLAY_POLICY
	,UPPER(P.POLH_ASSRDNM) AS INSURED_NAME
	--,P.POLH_DEBIT_PARTY
	,P.POLH_CLIENT
	,(SELECT C.CVBR_BRANCH_NAME FROM RAIMS.IBM_PARTY_BRANCH C WHERE C.CVBR_BRANCH_CODE=P.POLH_CLIENT) AS CLIENT_NAME
	,P.POLH_DEBIT_PARTY AS INTERMEDIARY_CODE
	,(SELECT C.CVBR_BRANCH_NAME FROM RAIMS.IBM_PARTY_BRANCH C WHERE C.CVBR_BRANCH_CODE=P.POLH_DEBIT_PARTY) AS INTERMEDIARY_NAME 
	,G.IH_JRNL_TYPE||P.POLH_PREM_DOCNUM AS INVOICE
	,P.POLH_SI_FC AS SUM_INSURED 
	,POLH_PREM_BC AS GROSS_PREMIUM
	,ROUND(P.POLH_PREM_BC+P.POLH_ADJ_PREM_BC,2) AS NET_PREMIUM 
	,P.POLH_ADJ_PREM_BC AS ADJUST_PREMIUM 
	,P.POLH_FEES3_BC AS ADMIN_FEE
	,(P.POLH_PREM_BC+P.POLH_ADJ_PREM_BC + P.POLH_FEES3_BC) AS TOTAL
	,TO_CHAR(P.POLH_ISSDT,'DD-MON-YYYY') AS ISSUE_DATE
	,TO_CHAR(P.POLH_STPERIOD,'DD-MON-YYYY') EFFECTIVE_DATE
	,TO_CHAR(P.POLH_ENDPERIOD,'DD-MON-YYYY') EXPIRY_DATE
	,P.POLH_EMPLOYEE AS ISSUE_BY
	,(SELECT U.USER_SHORT_NAME FROM RAIMS.MMGR_USERS U WHERE U.USER_ID=P.POLH_EMPLOYEE) AS USER_NAME
	--,P.*
	--(SELECT distinct(PINTMV_MOD_DESC) FROM INT_UW_PINT_MOTOR M WHERE M.PINTMV_PINT_SYS_ID=P.POLH_SYS_ID) AS DESCRIPTION
	--,M.PINTMV_MAKE_MODEL AS PINTMV_MAKE_MODEL
	--,M.PINTMV_MOD_DESC AS DESCRIPTION
	,P.POLH_UWYR
	FROM RAIMS.INT_UW_POLH P 
	--LEFT JOIN RAIMS.INT_UW_PINT_MOTOR M ON P.POLH_SYS_ID=M.PINTMV_PINT_SYS_ID
	INNER JOIN RAIMS.GLT_INTERFACE_HEAD G ON P.POLH_PREM_DOCNUM=G.IH_DOC_NO AND P.POLH_SYS_ID=G.IH_POLH_SYS_ID
	--WHERE 
	--P.POLH_EXTNUM=M.PINTMV_EXTNUM AND
	--P.POLH_STATUS IS NOT NULL AND
	--P.POLH_ISSDT BETWEEN '01-APR-2020' AND '30-APR-2020';
	--P.POLH_ISSDT BETWEEN '01-JUN-2020' AND '31-AUG-2020'; 
	--AND P.POLH_DISPLAY_POLNUM='P/01/PV00/20/0555/000/00';
	--AND P.POLH_DISPLAY_POLNUM='P/01/MC00/20/0043/000/00';
	--P.POLH_DISPLAY_POLNUM='P/01/PV00/20/0555/000/00';
*/
}

