SELECT
'DNU'||P.POLH_PREM_DOCNUM AS INVOICE,
P.POLH_DEBIT_PARTY AS ACCOUNT_CODE,
TO_CHAR(P.POLH_ISSDT,'DD-MON-YYYY') INVOICE_DATE,
--TO_CHAR(P.POLH_POST_PERIOD,'DD-MON-YYYY') AS ACC_MONTH_YEAR,
SUBSTR(POLH_POST_PERIOD,1,3) ||'-20'|| SUBSTR(POLH_POST_PERIOD,4,2) AS ACC_MONTH_YEAR,
UPPER(P.POLH_BENFNM) AS CUSTOMER_NAME,
replace(replace(P.POLH_ASSRD_ADDR,chr(10),' '),chr(13),' ') as ADDRESS,
'' AS VAT_TIN,
--'PRODUCT' AS PRODUCT,
(SELECT CLS_DESC FROM INM_MST_CLASS WHERE CLS_CODE=P.POLH_COB) AS PRODUCT,
P.POLH_DISPLAY_POLNUM AS POLICY_NO,
TO_CHAR(P.POLH_ISSDT,'DD-MON-YYYY') AS ISSUED_DATE,
TO_CHAR(P.POLH_STPERIOD,'DD-MON-YYYY') AS EFFECTIVE_DATE,
TO_CHAR(P.POLH_ENDPERIOD,'DD-MON-YYYY') AS EXPIRY_DATE,
--P.POLH_SI_FC AS CROSS_PREMIUM,
ROUND(P.POLH_PREM_FC,2) AS CROSS_PREMIUM,
'1.00' AS ADMIN_FEE,
(P.POLH_PREM_FC+1) AS TOTAL_DUE
FROM RAIMS.INT_UW_POLH P
WHERE P.POLH_DISPLAY_POLNUM=$P{parPolicyNumber}
--WHERE P.POLH_DISPLAY_POLNUM='P/01/PV00/20/0393/000/00'